# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cylinder',
                'doc_host': 'https://CJP123.github.io',
                'git_url': 'https://github.com/CJP123/cylinder',
                'lib_path': 'cylinder'},
  'syms': { 'cylinder.demand': {'cylinder.demand.load_demand': ('demand.html#load_demand', 'cylinder/demand.py')},
            'cylinder.hwc': { 'cylinder.hwc.HWC': ('hwc.html#hwc', 'cylinder/hwc.py'),
                              'cylinder.hwc.HWC.__init__': ('hwc.html#hwc.__init__', 'cylinder/hwc.py'),
                              'cylinder.hwc.HWC._thermostat': ('hwc.html#hwc._thermostat', 'cylinder/hwc.py'),
                              'cylinder.hwc.HWC._update_temperatures': ('hwc.html#hwc._update_temperatures', 'cylinder/hwc.py'),
                              'cylinder.hwc.HWC.reset': ('hwc.html#hwc.reset', 'cylinder/hwc.py')},
            'cylinder.index': {},
            'cylinder.power': {'cylinder.power.load_power': ('power.html#load_power', 'cylinder/power.py')}}}
