# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/100_ripple_control.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/100_ripple_control.ipynb 2
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from .utils import *
from scipy.stats import skew, skewnorm
